name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JDBC_DATABASE_URL: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Build with Gradle
      working-directory: ./app
      run: ./gradlew build
    
    - name: Run tests with Gradle
      working-directory: ./app
      run: ./gradlew test
    - name: SonarQube Scan
      working-directory: ./app
      run: ./gradlew sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
